# Generated by Django 5.2.5 on 2025-08-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0014_remove_kontakt_unique_kontakt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок вывода'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='ip_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Стационарный телефон'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='job_title',
            field=models.CharField(max_length=128, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='phone_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Мобильный Номер'),
        ),
    ]
