version: '3'

volumes:
  pg_data:
  static:

services:

  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: mo1exx/udmpf_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  gateway:
    image: mo1exx/udmpf_gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80
    depends_on:
      - backend