# Generated by Django 5.2.4 on 2025-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='ip_number',
            field=models.IntegerField(blank=True, verbose_name='Стационарный Телефон'),
        ),
    ]
