# Generated by Django 5.2.4 on 2025-07-24 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0002_alter_kontakt_ip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='e_mail',
            field=models.EmailField(blank=True, max_length=64, null=True, unique=True, verbose_name='Почта'),
        ),
    ]
