# Generated by Django 4.2.23 on 2025-07-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0003_alter_kontakt_e_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='ip_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стационарный Телефон'),
        ),
    ]
