# Generated by Django 4.2.23 on 2025-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0004_alter_kontakt_ip_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kontakt',
            name='job_title',
            field=models.CharField(max_length=64, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='kontakt',
            name='name',
            field=models.CharField(default=1, max_length=128, verbose_name='Имя'),
            preserve_default=False,
        ),
    ]
