# Generated by Django 4.2.23 on 2025-08-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0005_alter_kontakt_job_title_alter_kontakt_last_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ('-output_order',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='subdivision',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок вывода'),
        ),
    ]
