# Generated by Django 4.2.23 on 2025-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0006_alter_subdivision_options_subdivision_output_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-output_order',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AddField(
            model_name='department',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок вывода'),
        ),
    ]
