# Generated by Django 4.2.23 on 2025-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0008_alter_subdivision_output_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdivision',
            name='output_order',
            field=models.PositiveSmallIntegerField(default=100, verbose_name='Порядок вывода'),
        ),
    ]
