# Generated by Django 4.2.23 on 2025-08-04 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0009_alter_subdivision_output_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('output_order',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ('output_order',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
