# Generated by Django 4.2.23 on 2025-08-04 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0010_alter_department_options_alter_subdivision_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ('-output_order',), 'verbose_name': 'Отдел', 'verbose_name_plural': 'Отделы'},
        ),
        migrations.AlterModelOptions(
            name='subdivision',
            options={'ordering': ('-output_order',), 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
    ]
