# Generated by Django 4.2.23 on 2025-08-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0011_alter_department_options_alter_subdivision_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='kontakt',
            constraint=models.UniqueConstraint(fields=('last_name', 'name', 's_name'), name='unique_kontakt'),
        ),
    ]
