# Generated by Django 4.2.23 on 2025-08-05 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0012_kontakt_unique_kontakt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kontakt',
            name='unique_kontakt',
        ),
        migrations.AddConstraint(
            model_name='kontakt',
            constraint=models.UniqueConstraint(fields=('last_name', 'name', 's_name'), name='Unique kontakt'),
        ),
    ]
