# Generated by Django 4.2.23 on 2025-08-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0013_remove_kontakt_unique_kontakt_kontakt_unique_kontakt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='kontakt',
            name='Unique kontakt',
        ),
        migrations.AddConstraint(
            model_name='kontakt',
            constraint=models.UniqueConstraint(fields=('last_name', 'name', 's_name'), name='Unique kontakt constraint'),
        ),
    ]
