# Generated by Django 5.2.5 on 2025-09-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0015_kontakt_output_order_alter_kontakt_ip_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kontakt',
            name='pc_number',
            field=models.CharField(blank=True, null=True, verbose_name='Номер ПК'),
        ),
    ]
