# Generated by Django 5.2.5 on 2025-08-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='source',
            options={'ordering': ('title',), 'verbose_name': 'Информационный актив', 'verbose_name_plural': 'Информационные активы'},
        ),
    ]
